version: '2'
services:
  app:
    build: .
    command: rails server -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
    - db
    - redis
    environment:
      REDIS_URL: 'redis://redis:6379/0'
  sidekiq:
    depends_on:
      - redis
    build: .
    command: sidekiq
    volumes:
      - .:/app
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: nofity
      MYSQL_PASSWORD: nofity
      MYSQL_DATABASE: nofity_production
      MYSQL_ROOT_PASSWORD: nofity
  redis:
    image: redis:4.0.9
